spring:
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: none

 # datasource:
 #   url: jdbc:mysql://localhost:3306/pizzaria
 #   username: root
 #   password: paulistano@13
 #   driver-class-name: com.mysql.jdbc.Driver    
    
  datasource:
    url: jdbc:oracle:thin:@BD_SAUDEH_CORP.SULAMERICA.BR:1527/SAUDEH
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
        
server:
  servlet:
    context-path: /api/v1
  display-name: pizzaria
  port: 8080