spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/banco
    username: user
    password: senha
    driver-class-name: com.mysql.jdbc.Driver
        
server:
  servlet:
    context-path: /api/v1
  display-name: pizzaria
  port: 8080